# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=homepage.models.user_path)),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='\ud68c\uc0ac\uc18c\uac1c \uc81c\ubaa9')),
                ('text', models.TextField(blank=True, verbose_name='\ud68c\uc0ac\uc18c\uac1c \ub0b4\uc6a9')),
                ('history_title', models.CharField(blank=True, default='', max_length=200, verbose_name='\uc5f0\ud601 \uc81c\ubaa9')),
                ('history_sub_title', models.CharField(blank=True, default='', max_length=200, verbose_name='\uc5f0\ud601 \ubd80\uc81c\ubaa9')),
                ('history_text', models.TextField(verbose_name='\uc5f0\ud601 \ub0b4\uc6a9')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\ub4f1\ub85d\uc77c')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\uc218\uc815\uc77c')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\uc791\uc131\uc790')),
            ],
            options={
                'ordering': ('created_date',),
                'get_latest_by': ('created_date',),
                'verbose_name_plural': '\ud68c\uc0ac\uc18c\uac1c',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='\ud68c\uc0ac\uc774\ub984')),
                ('address', models.CharField(default='', max_length=20, verbose_name='\ud68c\uc0ac\uc8fc\uc18c')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='\uc774\uba54\uc77c')),
                ('delegate_number', models.CharField(blank=True, default='', max_length=20, verbose_name='\ub300\ud45c\uc804\ud654\ubc88\ud638')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\ub4f1\ub85d\uc77c')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\uc218\uc815\uc77c')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\uc791\uc131\uc790')),
            ],
            options={
                'ordering': ('created_date',),
                'get_latest_by': ('created_date',),
                'verbose_name_plural': '\ud68c\uc0ac\uc815\ubcf4',
            },
        ),
        migrations.CreateModel(
            name='Cta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\uc774\ub984')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='\uc804\ud654\ubc88\ud638')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='\uc774\uba54\uc77c')),
                ('subject', models.CharField(default='', max_length=200, verbose_name='\uc81c\ubaa9')),
                ('message', models.TextField(verbose_name='\ub0b4\uc6a9')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\ub4f1\ub85d\uc77c')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\uc218\uc815\uc77c')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\uc791\uc131\uc790')),
            ],
            options={
                'ordering': ('created_date',),
                'get_latest_by': ('created_date',),
                'verbose_name_plural': '\ubb38\uc758\uc0ac\ud56d',
            },
        ),
        migrations.CreateModel(
            name='EquipmentIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=200, verbose_name='\uc7a5\ube44\uc774\ub984')),
                ('company', models.CharField(default='', max_length=20, verbose_name='\uc81c\uc870\ud68c\uc0ac')),
                ('boom', models.IntegerField(default=0, verbose_name='\uae30\ubcf8\ubd90')),
                ('radius', models.IntegerField(default=0, verbose_name='\ucd5c\ub300\uc791\uc5c5\ubc18\uacbd')),
                ('capacity', models.IntegerField(default=0, verbose_name='\ucd5c\ub300\uc778\uc591\ub2a5\ub825')),
                ('xls_file', models.FileField(blank=True, upload_to=homepage.models.user_path, validators=[homepage.models.validate_file_extension], verbose_name='\uc5d1\uc140\ud30c\uc77c')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\ub4f1\ub85d\uc77c')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\uc218\uc815\uc77c')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\uc791\uc131\uc790')),
            ],
            options={
                'ordering': ('created_date',),
                'get_latest_by': ('created_date',),
                'verbose_name_plural': '\uc7a5\ube44\uc18c\uac1c',
            },
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='\uc7a5\ube44\uba85')),
                ('standard', models.CharField(default='', max_length=200, verbose_name='\uaddc\uaca9')),
                ('form', models.CharField(default='', max_length=200, verbose_name='\ud615\uc2dd')),
                ('producer', models.CharField(default='', max_length=200, verbose_name='\uc81c\uc791\uc0ac')),
                ('equipment_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.About')),
            ],
            options={
                'verbose_name_plural': '\uc7a5\ube44\ub9ac\uc2a4\ud2b8',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=homepage.models.user_path, verbose_name='\uba54\uc778\uc0ac\uc9c4')),
                ('title', models.CharField(max_length=200, verbose_name='\uba54\uc778\uc81c\ubaa9')),
                ('text', models.TextField(verbose_name='\uba54\uc778\ub0b4\uc6a9')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\ub4f1\ub85d\uc77c')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\uc218\uc815\uc77c')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\uc791\uc131\uc790')),
            ],
            options={
                'ordering': ('created_date',),
                'get_latest_by': ('created_date',),
                'verbose_name_plural': '\uba54\uc778\ud398\uc774\uc9c0',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=homepage.models.user_path, validators=[homepage.models.validate_file_extension], verbose_name='\uc7a5\ube44\uc0ac\uc9c4')),
                ('image_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.EquipmentIntro')),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=100, verbose_name='\uc804\ud654\ubc88\ud638')),
                ('phone_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.CompanyInfo')),
            ],
        ),
    ]
