# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 04:15
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=homepage.models.user_path)),
                ('title', models.CharField(max_length=200, verbose_name='\ud68c\uc0ac\uc18c\uac1c \uc81c\ubaa9')),
                ('text', models.TextField(verbose_name='\ud68c\uc0ac\uc18c\uac1c \ub0b4\uc6a9')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\uc791\uc131\uc790')),
            ],
            options={
                'verbose_name_plural': '\ud68c\uc0ac\uc18c\uac1c',
            },
        ),
        migrations.CreateModel(
            name='EquipmentIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=200, verbose_name='\uc7a5\ube44\uc774\ub984')),
                ('company', models.CharField(default='', max_length=20, verbose_name='\uc81c\uc870\ud68c\uc0ac')),
                ('boom', models.IntegerField(default=0, verbose_name='\uae30\ubcf8\ubd90')),
                ('radius', models.IntegerField(default=0, verbose_name='\ucd5c\ub300\uc791\uc5c5\ubc18\uacbd')),
                ('capacity', models.IntegerField(default=0, verbose_name='\ucd5c\ub300\uc778\uc591\ub2a5\ub825')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\ub4f1\ub85d\uc77c')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\uc218\uc815\uc77c')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\uc791\uc131\uc790')),
            ],
            options={
                'ordering': ('created_date',),
                'get_latest_by': ('created_date',),
                'verbose_name_plural': '\uc7a5\ube44\uc18c\uac1c',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=homepage.models.user_path, verbose_name='\uba54\uc778\uc0ac\uc9c4')),
                ('title', models.CharField(max_length=200, verbose_name='\uba54\uc778\uc81c\ubaa9')),
                ('text', models.TextField(verbose_name='\uba54\uc778\ub0b4\uc6a9')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\uc791\uc131\uc790')),
            ],
            options={
                'verbose_name_plural': '\uba54\uc778\ud398\uc774\uc9c0',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=homepage.models.user_path, verbose_name='\uc7a5\ube44\uc0ac\uc9c4')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.EquipmentIntro')),
            ],
        ),
    ]
