# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171001_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='thumname_image',
        ),
    ]
