# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171018_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentimage',
            name='image_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.EquipmentIntro'),
        ),
    ]
