# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20171019_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentImage',
            new_name='Images',
        ),
    ]
