# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20171019_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentintro',
            name='xlsfile',
            field=models.FileField(blank=True, upload_to=homepage.models.user_path, validators=[homepage.models.validate_file_extension], verbose_name='\uc5d1\uc140\ud30c\uc77c'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to=homepage.models.user_path, validators=[homepage.models.validate_file_extension], verbose_name='\uc7a5\ube44\uc0ac\uc9c4'),
        ),
    ]
