# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, upload_to=homepage.models.user_path),
        ),
    ]
