# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20171002_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': '\ud68c\uc0ac\uc18c\uac1c'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': '\uba54\uc778\ud398\uc774\uc9c0'},
        ),
        migrations.AlterField(
            model_name='home',
            name='author',
            field=models.ForeignKey(default='crane', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\uc791\uc131\uc790'),
        ),
        migrations.AlterField(
            model_name='home',
            name='photo',
            field=models.ImageField(upload_to=homepage.models.user_path, verbose_name='\uba54\uc778\uc0ac\uc9c4'),
        ),
        migrations.AlterField(
            model_name='home',
            name='text',
            field=models.TextField(verbose_name='\uba54\uc778\ub0b4'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\uba54\uc778\uc81c\ubaa9'),
        ),
    ]
