# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0006_auto_20171002_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=homepage.models.user_path)),
                ('title', models.CharField(max_length=200, verbose_name='\uc7a5\ube44\uc18c\uac1c \uc81c\ubaa9')),
                ('text', models.TextField(verbose_name='\uc7a5\ube44\uc18c\uac1c \ub0b4\uc6a9')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(default='crane', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '\uc7a5\ube44\uc18c\uac1c',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(verbose_name='\ud68c\uc0ac\uc18c\uac1c \ub0b4\uc6a9'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\ud68c\uc0ac\uc18c\uac1c \uc81c\ubaa9'),
        ),
        migrations.AlterField(
            model_name='home',
            name='text',
            field=models.TextField(verbose_name='\uba54\uc778\ub0b4\uc6a9'),
        ),
    ]
