# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20171003_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentintro',
            name='text',
        ),
        migrations.RemoveField(
            model_name='equipmentintro',
            name='title',
        ),
        migrations.AddField(
            model_name='equipmentintro',
            name='boom',
            field=models.CharField(default='', max_length=20, verbose_name='\uae30\ubcf8\ubd90'),
        ),
        migrations.AddField(
            model_name='equipmentintro',
            name='capacity',
            field=models.CharField(default='', max_length=20, verbose_name='\ucd5c\ub300\uc778\uc591\ub2a5\ub825'),
        ),
        migrations.AddField(
            model_name='equipmentintro',
            name='company',
            field=models.CharField(default='', max_length=20, verbose_name='\uc81c\uc870\ud68c\uc0ac'),
        ),
        migrations.AddField(
            model_name='equipmentintro',
            name='model',
            field=models.CharField(default='', max_length=200, verbose_name='\uc7a5\ube44\uc774\ub984'),
        ),
        migrations.AddField(
            model_name='equipmentintro',
            name='radius',
            field=models.CharField(default='', max_length=20, verbose_name='\ucd5c\ub300\uc791\uc5c5\ubc18\uacbd'),
        ),
    ]
