# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20171003_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='equipmentintro',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='home',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='equipmentintro',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\ub4f1\ub85d\uc77c'),
        ),
        migrations.AlterField(
            model_name='equipmentintro',
            name='photo',
            field=models.ImageField(blank=True, upload_to=homepage.models.user_path, verbose_name='\uc7a5\ube44\uc0ac\uc9c4'),
        ),
    ]
